In [20]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [21]:
# Imports
import torch.nn as nn

In [22]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [23]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [24]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [25]:
# Define dataset

train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [26]:
# Define data loader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 91.,  88.,  64.],
         [ 69.,  96.,  70.],
         [ 69.,  96.,  70.]]), tensor([[119., 133.],
         [ 22.,  37.],
         [ 81., 101.],
         [103., 119.],
         [103., 119.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [27]:
# Define model

model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1699,  0.4494, -0.2616],
        [-0.2582,  0.2531, -0.3552]], requires_grad=True)
Parameter containing:
tensor([ 0.5547, -0.4307], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [28]:
# Define optimizer

opt = torch.optim.SGD(model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [29]:
# Import nn.functional
import torch.nn.functional as F

In [30]:
# Define loss function
loss_fn = F.mse_loss

In [31]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(7725.5864, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [32]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
   for epoch in range(num_epochs):
       for xb,yb in train_dl:
           # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred,yb)
           # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
   print('Training loss: ', loss_fn(model(inputs), targets))

In [33]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Training loss:  tensor(49.7015, grad_fn=<MseLossBackward>)


In [34]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.4742,  71.1669],
        [ 78.2665,  95.8775],
        [124.4572, 141.1452],
        [ 28.5347,  42.9322],
        [ 90.9044, 107.3597],
        [ 58.4742,  71.1669],
        [ 78.2665,  95.8775],
        [124.4572, 141.1452],
        [ 28.5347,  42.9322],
        [ 90.9044, 107.3597],
        [ 58.4742,  71.1669],
        [ 78.2665,  95.8775],
        [124.4572, 141.1452],
        [ 28.5347,  42.9322],
        [ 90.9044, 107.3597]], grad_fn=<AddmmBackward>)

In [35]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [36]:
fit(100, model, loss_fn, opt)

Training loss:  tensor(25.3795, grad_fn=<MseLossBackward>)


In [37]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.8584,  70.8472],
        [ 79.0968,  97.1320],
        [125.1320, 140.5935],
        [ 23.8320,  39.8029],
        [ 94.9794, 111.2389],
        [ 57.8584,  70.8472],
        [ 79.0968,  97.1320],
        [125.1320, 140.5935],
        [ 23.8320,  39.8029],
        [ 94.9794, 111.2389],
        [ 57.8584,  70.8472],
        [ 79.0968,  97.1320],
        [125.1320, 140.5935],
        [ 23.8320,  39.8029],
        [ 94.9794, 111.2389]], grad_fn=<AddmmBackward>)

In [38]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 