#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)

In [1]:
# Import Numpy
import numpy as np

## Linear Regression Model using numpy

Re-implementing the same model using numpy using two different targets: Apples and Oranges

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [3]:
# getting x-shape

x_shape = inputs.shape
print(x_shape)

(15, 3)


Getting Random Weights and biases

In [4]:
weights = np.random.rand(2,3)
weights

array([[0.07786256, 0.23675037, 0.69496506],
       [0.09820338, 0.12884643, 0.2574114 ]])

In [5]:
biases = np.random.rand(15,2)
biases

array([[0.98152025, 0.98618066],
       [0.13191345, 0.54870707],
       [0.58503032, 0.67053756],
       [0.7723728 , 0.23522464],
       [0.03804859, 0.74355128],
       [0.33866407, 0.14390927],
       [0.35385489, 0.79666648],
       [0.69630766, 0.17416131],
       [0.19488942, 0.24786164],
       [0.30939193, 0.99897466],
       [0.84039179, 0.83324891],
       [0.30302146, 0.00508709],
       [0.43419817, 0.3732702 ],
       [0.80558856, 0.49447149],
       [0.7601755 , 0.80422864]])

Linear Regression Model

In [6]:
# Define the model

def model(x):
    return x @ np.transpose(weights) + biases

In [7]:
# Generate predictions

preds = model(inputs)
print(preds)

[[52.41125882 27.85642807]
 [72.5292019  37.29802963]
 [79.39159511 41.40951408]
 [44.60832631 25.31658724]
 [76.7861541  37.90763939]
 [51.76840264 27.01415668]
 [72.75114335 37.54598904]
 [79.50287245 40.91313783]
 [44.03084294 25.32922425]
 [77.05749744 38.16306276]
 [52.27013035 27.70349632]
 [72.70030992 36.75440965]
 [79.24076296 41.11224672]
 [44.64154208 25.5758341 ]
 [77.50828102 37.96831675]]


In [8]:
# Compare with targets

print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


# Loss Function

We can compare the predictions with the actual targets, using the following method: 
* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [9]:
# MSE loss

def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [10]:
# Compute loss

loss = mse(preds, targets)
print(loss)

4766.598342557376


# Compute Gradiants

Gradiants for weights

In [11]:
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]
weights_grad

array([[ -1594.16594944,  -3128.61190559,  -1591.7376071 ],
       [ -9467.39983604, -11616.84291804,  -6934.11450287]])

Gradiants for biases

In [12]:
biases_grad = (preds-targets)*2/x_shape[0]
biases_grad

array([[ -0.47849882,  -5.61914292],
       [ -1.12943975,  -8.49359605],
       [ -5.28112065, -12.21206479],
       [  3.01444351,  -1.55778837],
       [ -3.49517945, -10.81231475],
       [ -0.56421298,  -5.73144578],
       [ -1.09984755,  -8.46053479],
       [ -5.26628367, -12.27824829],
       [  2.93744572,  -1.55610343],
       [ -3.45900034, -10.7782583 ],
       [ -0.49731595,  -5.63953382],
       [ -1.10662534,  -8.56607871],
       [ -5.30123161, -12.25170044],
       [  3.01887228,  -1.52322212],
       [ -3.39889586, -10.80422443]])

# Adjust Weights using Gradints

In [13]:
weights -= weights_grad * 1e-5
weights

array([[0.09380421, 0.26803649, 0.71088243],
       [0.19287737, 0.24501486, 0.32675254]])

In [14]:
biases -= biases_grad * 1e-5
biases

array([[0.98152504, 0.98623685],
       [0.13192474, 0.548792  ],
       [0.58508314, 0.67065969],
       [0.77234266, 0.23524022],
       [0.03808354, 0.7436594 ],
       [0.33866972, 0.14396659],
       [0.35386589, 0.79675109],
       [0.69636032, 0.17428409],
       [0.19486005, 0.24787721],
       [0.30942652, 0.99908244],
       [0.84039676, 0.83330531],
       [0.30303253, 0.00517275],
       [0.43425118, 0.37339271],
       [0.80555838, 0.49448673],
       [0.76020949, 0.80433668]])

Calculate Loss

In [15]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

2402.890215591477


In [16]:
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

Calculate Loss

In [17]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

14.336919153509632


Printing Predictions

In [18]:
preds

array([[ 58.11681542,  71.60357874],
       [ 82.74776218,  98.92881817],
       [115.99850053, 135.73543481],
       [ 23.62907662,  40.86110382],
       [101.80826951, 113.97887246],
       [ 57.47413151,  70.76153305],
       [ 82.96964416,  99.17671114],
       [116.10974805, 135.23919157],
       [ 23.05174799,  40.87373744],
       [102.07954015, 114.23422739],
       [ 57.97572478,  71.45068797],
       [ 82.91882435,  98.38534386],
       [115.84770879, 135.43824709],
       [ 23.66228349,  41.1202812 ],
       [102.53020293, 114.03953356]])

Compare with targets

In [19]:
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)